services:
  postgresql:
    image: postgres
    container_name: crypto-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crypto